"""Generate the GameScript hotkey body for the sprite placement / palette probe.

The probe is a *diagnostic ladder*, not a single measurement. The 2026-09-16 run failed
because a custom terrain sprite type built from an injected archive member registered an id
but rendered nothing, and there was no control that could say why. Four sprite types are now
placed side by side in one capture:

    zt0  shipped type, shipped art      terrainsprites /orchard get
    zt1  custom type,  shipped art      ["imp/tree4e.imp"] cvx addterrainspritetype
    zt2  custom type,  injected copy    ["imp/zzctl.imp"]  cvx addterrainspritetype
    zt3  custom type,  authored palette ["imp/zzpal.imp"]  cvx addterrainspritetype

Whichever rung the ladder breaks on names the cause: the operator, the injection, or the
palette edit. `zzctl.imp` is byte-identical to `imp\\tree4e.imp`, so zt1 versus zt2 isolates
"the engine cannot read an added member" from "our edit broke the file".

Two hazards the previous run walked into, both fixed here:

- `anythingat?` does **not** see terrain sprites, so a cell can read empty and still hold a
  village. `terrainspriteat` then handed back somebody else's outpost and it was destroyed, so
  cleanup never matches on location alone. It does not match on **type** alone either: rung 0
  reuses the *shipped* orchard type, and destroying by that type would delete every orchard the
  map generator placed. Cleanup requires type **and** cell; only the freshly registered ids get
  a second type-only sweep, since nothing else on the map can be carrying them.
- The hotkey auto-repeats while the key is held. A `zdone` flag in `userdict` makes the body
  fire exactly once per launch.

**Locations are packed, not pairs.** `anythinglocation` and `getterrainspritelocation` each
return ONE value, `y * map_width + x`, and `findemptylocation` takes `(location, unittype)` --
two operands. The shipped corpus is the authority here: `anythinglocation xy_to_x_y` appears 31
times, and `/temple_loc temple_id getterrainspritelocation def` stores a single scalar. The
recovered arity table undercounts and must not be used to design an operand order. Reading a
packed location as a pair underflows the stack and kills the body silently: the 2026-09-16 run
logged an empty x beside `9152`, which at map width 128 is cell (64,71).
"""

from __future__ import annotations

# (label, GameScript expression yielding a terrain sprite type id)
SPRITE_TYPES: list[tuple[str, str]] = [
    ("shipped_type_shipped_art", "terrainsprites /orchard get"),
    ("custom_type_shipped_art", '["imp/tree4e.imp"]cvx addterrainspritetype'),
    ("custom_type_injected_copy", '["imp/zzctl.imp"]cvx addterrainspritetype'),
    ("custom_type_authored_palette", '["imp/zzpal.imp"]cvx addterrainspritetype'),
]

# Seed offsets from the army cell, one per sprite type. `findemptylocation` walks outward from each
# seed, so the seeds have to be far enough apart that two rungs cannot converge on one cell -- two
# sprites in the same cell makes the ladder unreadable. A cell is about 34 screen pixels of x, and
# the donor frame is 72 wide, so 2 cells is the minimum separation and 4 is comfortable. Laying them
# along one axis also gives four collinear points for the cell-to-screen fit.
SEED_OFFSETS: list[tuple[int, int]] = [(2, 0), (4, 0), (-2, 0), (-4, 0)]

HOTKEY = "z"


def is_freshly_registered(index: int) -> bool:
    """True when the type id is minted by this keypress rather than reused from the game.

    Only a freshly registered id is safe to clean up by type alone: no sprite the probe did not
    place can be carrying it. Rung 0 deliberately reuses a shipped type, and is therefore the one
    rung that must always be matched by cell as well.
    """
    return "addterrainspritetype" in SPRITE_TYPES[index][1]


def _log(text: str) -> str:
    """One `zprobe.log` line. `build_statement` interpolates the non-string tokens."""
    return f"zlog{{{text}}}build_statement writestring zlog carriage_return"


def probe_body() -> str:
    lines: list[str] = []
    emit = lines.append

    emit("; ---- BEGIN SPRITE PLACEMENT PROBE (generated by tools/engine_probe.py) ----")
    emit(f'ASCII_VAL"{HOTKEY}"0 get')
    emit("{")
    emit("userdict /zdone known not")
    emit("\t{")
    emit("\tuserdict begin")
    emit("\t/zdone true def")
    emit('\t"zprobe.log""abw"file /zlog exch def')

    # Settle the map first. The previous plate was captured before any rendermap, so the whole
    # terrain sprite layer appeared in the difference and swamped the subject.
    emit("\trendermap refreshdirty")
    emit('\t"zp0.bmp"screencapture')

    # `anythinglocation` returns ONE PACKED LOCATION, not an x/y pair. The shipped corpus settles it
    # -- `anythinglocation xy_to_x_y` appears 31 times, and you do not decompose an already
    # decomposed pair. The 2026-09-16 run proves it too: its log line printed an empty x and
    # y=9152, which at map width 128 is cell (64,71). Reading it as a pair underflows the stack and
    # kills the body before the first placement.
    emit("\t/zaloc -1 def /zseen false def")
    emit(
        "\tcurrentplayer{zseen not{anythinglocation /zaloc exch def /zseen true def}"
        "{pop}ifelse}enumplayerarmies"
    )
    emit("\tzseen")
    emit("\t\t{")
    emit("\t\tzaloc xy_to_x_y /zay0 exch def /zax0 exch def")
    emit("\t\t" + _log('"army loc "zaloc" cell "zax0" "zay0'))

    for index, ((label, expression), (dx, dy)) in enumerate(
        zip(SPRITE_TYPES, SEED_OFFSETS), start=0
    ):
        emit(f"\t\t{expression} /zt{index} exch def")
        # `findemptylocation` takes (location, unittype) -- two operands, not three. Shipped form:
        # `unit_loc UNITTYPELAND findemptylocation /unit_loc exch def`. `x_y_to_xy` packs the pair.
        emit(
            f"\t\tzax0 {dx} add zay0 {dy} add x_y_to_xy UNITTYPELAND findemptylocation "
            f"/zl{index} exch def"
        )
        emit(f"\t\tzl{index} xy_to_x_y /zy{index} exch def /zx{index} exch def")
        emit(f"\t\tzx{index} zy{index} 0 map2screen /zm3 exch def /zm2 exch def /zm1 exch def")
        emit(
            "\t\t"
            + _log(
                f'"type {index} {label} id "zt{index}" loc "zl{index}'
                f'" cell "zx{index}" "zy{index}" m2s "zm1" "zm2" "zm3'
            )
        )
        # Place before resolving the next rung, so `findemptylocation` has a chance to route around
        # a cell this probe just filled.
        emit(f"\t\tzx{index} zy{index} zt{index} addterrainsprite")

    emit("\t\trendermap refreshdirty")
    emit('\t\t"zs1.bmp"screencapture')

    # Cleanup must match the type *and* the cell the probe placed it on. Matching on location alone
    # destroyed a village; matching on type alone is worse, because rung 0 reuses the **shipped**
    # orchard type and would delete every orchard the map generator placed.
    # `getterrainspritelocation` also returns ONE packed location -- shipped uses are
    # `/temple_loc temple_id getterrainspritelocation def` and `... getterrainspritelocation 4 mod`.
    # Compare it against the packed cell the probe placed on, not against a decomposed pair.
    for index in range(len(SPRITE_TYPES)):
        emit(
            f"\t\t{{dup getterrainspritetype zt{index} eq"
            f"{{dup getterrainspritelocation zl{index} eq"
            "{destroyterrainsprite}{pop}ifelse}"
            "{pop}ifelse}enumterrainsprites"
        )
    # A second, type-only pass for the three freshly registered types. Their ids were minted by this
    # keypress, so nothing else on the map can carry them, and it catches anything the first pass
    # skipped -- destroying during an enumeration may advance past an entry.
    for index in range(len(SPRITE_TYPES)):
        if not is_freshly_registered(index):
            continue
        emit(
            f"\t\t{{dup getterrainspritetype zt{index} eq"
            "{destroyterrainsprite}{pop}ifelse}enumterrainsprites"
        )
    emit("\t\trendermap refreshdirty")
    emit('\t\t"zs2.bmp"screencapture')
    emit("\t\t" + _log('"cleanup done"'))
    emit("\t\t}")
    # No army means no anchor cell, so say so in the log rather than placing at (-1,-1).
    emit("\t\t{" + _log('"no army found; nothing placed"') + "}ifelse")

    emit("\tzlog closefile")
    emit("\tend")
    emit("\t}if")
    emit("}addhotkey")
    emit("; ---- END SPRITE PLACEMENT PROBE ----")
    return "\n".join(lines) + "\n"



# --- elevation probe -------------------------------------------------------------------------
#
# The ladder run settled the compositing questions and left one thing open: the measured anchor y
# is not linear in the cell (156, 167, 230, 265 across cells 60, 62, 66, 68 of a single row) while
# `map2screen`'s first two outputs are perfectly linear at 14.4 per isometric step. Terrain
# elevation is the candidate, and the probe passed `z = 0`.
#
# This probe tests that directly rather than fitting a curve to it. For a neighbourhood of cells it
# logs `getelevation` beside `map2screen` called BOTH ways -- once with z = 0, once with z set to
# that cell's elevation. If the elevation-fed call predicts the anchors we then measure from real
# placements, the z input is identified and the y convention closes.

# Offsets for the placements. Screen x moves by 33.941 * (dx - dy), so these six are distinct on
# screen, spread over both axes, and separated by more than the 72-pixel frame width.
PLACEMENT_OFFSETS: list[tuple[int, int]] = [(-6, 0), (-3, 0), (3, 0), (6, 0), (0, 3), (0, -3)]

# Half-width of the surveyed square. The survey places nothing, so it is nearly free.
SURVEY_RADIUS = 4

# One custom type built from shipped art, which the ladder run proved renders.
ELEVATION_SPRITE = '["imp/tree4e.imp"]cvx addterrainspritetype'


def elevation_body() -> str:
    lines: list[str] = []
    emit = lines.append

    emit("; ---- BEGIN ELEVATION PROBE (generated by tools/engine_probe.py) ----")
    emit(f'ASCII_VAL"{HOTKEY}"0 get')
    emit("{")
    emit("userdict /zdone known not")
    emit("\t{")
    emit("\tuserdict begin")
    emit("\t/zdone true def")
    emit('\t"zprobe.log""abw"file /zlog exch def')
    emit("\trendermap refreshdirty")
    emit('\t"zp0.bmp"screencapture')
    emit("\t/zaloc -1 def /zseen false def")
    emit(
        "\tcurrentplayer{zseen not{anythinglocation /zaloc exch def /zseen true def}"
        "{pop}ifelse}enumplayerarmies"
    )
    emit("\tzseen")
    emit("\t\t{")
    emit("\t\tzaloc xy_to_x_y /zay0 exch def /zax0 exch def")
    emit("\t\t" + _log('"army loc "zaloc" cell "zax0" "zay0'))

    # The field survey: elevation and both map2screen calls for every cell in the neighbourhood.
    # Nothing is placed, so this costs only log lines and cannot disturb the map.
    radius = SURVEY_RADIUS
    emit(f"\t\t{-radius} 1 {radius}{{/zdy exch def")
    emit(f"\t\t{-radius} 1 {radius}{{/zdx exch def")
    emit("\t\t/zcx zax0 zdx add def /zcy zay0 zdy add def")
    emit("\t\tzcx zcy getelevation /ze exch def")
    emit("\t\tzcx zcy 0 map2screen /zb3 exch def /zb2 exch def /zb1 exch def")
    emit("\t\tzcx zcy ze map2screen /zn3 exch def /zn2 exch def /zn1 exch def")
    emit(
        "\t\t"
        + _log(
            '"field "zcx" "zcy" elev "ze" z0 "zb1" "zb2" "zb3" ze "zn1" "zn2" "zn3'
        )
    )
    emit("\t\t}for")
    emit("\t\t}for")

    # The placements, which are what actually measure an anchor.
    emit(f"\t\t{ELEVATION_SPRITE} /zt exch def")
    for index, (dx, dy) in enumerate(PLACEMENT_OFFSETS):
        emit(
            f"\t\tzax0 {dx} add zay0 {dy} add x_y_to_xy UNITTYPELAND findemptylocation "
            f"/zl{index} exch def"
        )
        emit(f"\t\tzl{index} xy_to_x_y /zy{index} exch def /zx{index} exch def")
        emit(f"\t\tzx{index} zy{index} getelevation /ze{index} exch def")
        emit(f"\t\tzx{index} zy{index} 0 map2screen /zb3 exch def /zb2 exch def /zb1 exch def")
        emit(
            f"\t\tzx{index} zy{index} ze{index} map2screen "
            "/zn3 exch def /zn2 exch def /zn1 exch def"
        )
        emit(
            "\t\t"
            + _log(
                f'"place {index} loc "zl{index}" cell "zx{index}" "zy{index}'
                f'" elev "ze{index}" z0 "zb1" "zb2" "zb3" ze "zn1" "zn2" "zn3'
            )
        )
        emit(f"\t\tzx{index} zy{index} zt addterrainsprite")
    emit("\t\trendermap refreshdirty")
    emit('\t\t"zs1.bmp"screencapture')

    # `zt` was minted by this keypress, so a type-only sweep cannot touch anything of the game's.
    # The cell-qualified pass runs first anyway, for the same reason it does in the ladder.
    for index in range(len(PLACEMENT_OFFSETS)):
        emit(
            f"\t\t{{dup getterrainspritetype zt eq"
            f"{{dup getterrainspritelocation zl{index} eq"
            "{destroyterrainsprite}{pop}ifelse}"
            "{pop}ifelse}enumterrainsprites"
        )
    emit(
        "\t\t{dup getterrainspritetype zt eq"
        "{destroyterrainsprite}{pop}ifelse}enumterrainsprites"
    )
    emit("\t\trendermap refreshdirty")
    emit('\t\t"zs2.bmp"screencapture')
    emit("\t\t" + _log('"cleanup done"'))
    emit("\t\t}")
    emit("\t\t{" + _log('"no army found; nothing placed"') + "}ifelse")
    emit("\tzlog closefile")
    emit("\tend")
    emit("\t}if")
    emit("}addhotkey")
    emit("; ---- END ELEVATION PROBE ----")
    return "\n".join(lines) + "\n"

# --- oversized map probe ---------------------------------------------------------------------
#
# Issue #22 asks whether a map larger than the original maximum omits the four-byte word at 0x00,
# shifting every later offset. It was parked for want of an oversized map. It does not need one
# from outside: the shipped GS5R3 editor generates 32 to 1024 in steps of 32, and both halves of
# the operation are reachable from script.
#
# Operand orders come from shipped call sites, which is the only source allowed to settle them:
#
#     gs\edit\mapgen.gs:306   newmapdict begin map_width 32 mul map_height 32 mul end
#                              make_custom_random_map          -- width first
#     gs\rmg.gs               /map_custom_parameters{/mh exch def /mw exch def ...}
#                                                              -- pops height, then width
#     gs\hotkey.gs:562        mapfilename savescenariomap     -- one string, pushes a result
#
# This is a ladder, not a measurement. 128 is the size every shipped world map uses and 256 is the
# largest in the corpus, so both can be compared against files the game itself shipped. If a
# generated 128 does not match the shipped 128 layout, the generator is not a faithful writer and
# nothing the 512 says can be trusted -- that is the control, and it has to come first. 512 is the
# subject. Whichever rung fails names the cause.
MAP_SIZES: list[int] = [128, 256, 512]

# `savescenariomap` takes the string buffer idiom every shipped call site uses -- `/mapfilename 100
# string def`, filled by `strcpy` -- rather than a bare literal. Same type either way, but the probe
# does not get to find that out the hard way on an attended run.
MAP_NAME_BUFFER = 100


def generate_call(width: int, height: int) -> str:
    """The generator call, width first.

    Factored out so the operand order can be tested with unequal arguments. Every size in the
    ladder is square, so a test written against the ladder alone would pass just as happily with
    the operands transposed -- and this is exactly the kind of order the arity table cannot settle
    and a shipped call site had to (`gs\\edit\\mapgen.gs:306`).
    """
    return f"{width} {height} make_custom_random_map"


def generated_map_names() -> list[str]:
    """Exactly the map files the mapsize probe writes, as `map/`-relative names.

    The install and restore scripts clear and collect by this list rather than by a `zz*.scn`
    glob. A glob is a standing offer to delete somebody's `zzCustom.scn`, and the game's loose
    `map/` directory has no backup: the manifest covers `gs.mpq` and `imp.mpq` only. An exact
    list can only ever match files this probe created.
    """
    return [f"map/zz{size}.scn" for size in MAP_SIZES]


def map_size_body() -> str:
    lines: list[str] = []
    emit = lines.append

    emit("; ---- BEGIN OVERSIZED MAP PROBE (generated by tools/engine_probe.py) ----")
    emit(f'ASCII_VAL"{HOTKEY}"0 get')
    emit("{")
    emit("userdict /zdone known not")
    emit("\t{")
    emit("\tuserdict begin")
    emit("\t/zdone true def")
    emit('\t"zprobe.log""abw"file /zlog exch def')
    emit(f"\t/zname {MAP_NAME_BUFFER} string def")
    emit("\t" + _log('"map size ladder start"'))

    for size, map_name in zip(MAP_SIZES, generated_map_names()):
        # The log is closed and reopened around every rung. `savescenariomap` on a 512 is the rung
        # most likely to fault or hang -- it is the one the editor itself warns about -- and an
        # unflushed buffer would take the 128 and 256 control results down with it. The ladder is
        # worth nothing if a failure on the subject erases the controls. "abw" appends.
        emit("\t" + _log(f'"gen begin "{size}'))
        # No `clearmap` here. The editor's generate branch calls `0 clearmap` first, but only to
        # blank a map it already has loaded; `make_random_map` opens with `mw mh newmap` itself
        # (gs\rmg.gs), so clearmap is redundant -- and it reads `mapw`/`maph`, which makes it a
        # precondition on there already being a map. The probe should not need one.
        emit("\t" + generate_call(size, size))
        emit("\tresetvisibility rendermap")
        # `mapw`/`maph` are the engine's own view of the live map. If the engine silently clamped
        # the request, this is where it shows, and it separates "the generator refused" from "the
        # file is written differently".
        emit("\t" + _log(f'"gen done "{size}" mapw "mapw" maph "maph'))
        emit(f'\tzname"{map_name}"strcpy')
        # All six shipped call sites read `savescenariomap pop`, so it pushes exactly one value.
        # Keeping it rather than popping it is the only way to learn that a save failed.
        emit("\tzname savescenariomap /zok exch def")
        # The filename is NOT interpolated. `zname` is a 100-byte buffer holding a 13-character
        # name; whether `writestring` emits the ~87 padding bytes or stops at the first of them,
        # the result value at the end of the line is what gets lost. It is a constant here anyway.
        emit("\t" + _log(f'"save "{size}" name {map_name} result "zok'))
        emit(f'\t"zm{size}.bmp"screencapture')
        emit("\tzlog closefile")
        emit('\t"zprobe.log""abw"file /zlog exch def')

    emit("\t" + _log('"map size ladder done"'))
    emit("\tzlog closefile")
    emit("\tend")
    emit("\t}if")
    emit("}addhotkey")
    emit("; ---- END OVERSIZED MAP PROBE ----")
    return "\n".join(lines) + "\n"


# --- flat ground probe -------------------------------------------------------------------------
#
# `map2screen` is decoded, and the drawn screen x matches its third output to under a pixel. The
# drawn y only approximately matches the second output: fitting six placements gave residuals up to
# 11 pixels, and two placements sharing an `x + y` were drawn 24 pixels apart while output 2
# differed by 5.09. No rescaling of output 2 produces that.
#
# The candidate is that the renderer interpolates height across the terrain mesh instead of
# sampling the anchor cell. That hypothesis has a counter-example in hand, because it was tested
# against a map nobody chose: the elevation run measured a shipped world map, surveyed its
# neighbourhoods afterwards, and two of its six placements fell outside the surveyed square.
#
# So this probe does not measure a map. It BUILDS one. `newmap` and `setelevation` mean the mesh is
# specified rather than reconstructed, and the same six cells are then photographed three times:
#
#   A  flat        every cell 0            -- calibrates drawn y against output 2 with no z term
#   B  plateau     a uniform block at E    -- cell elevation E, neighbourhood also E
#   C  spikes      only the six cells at E -- cell elevation E, neighbourhood 0
#
# A against B gives the z term where cell and neighbourhood agree. **B against C is the whole
# experiment**: identical `getelevation` at every placement cell, identical screen x, and the only
# difference is what surrounds them. If the drawn y moves, the renderer is reading the mesh and not
# the cell, and the size of the move measures it. If it does not, interpolation is dead and the
# missing term is something else.
#
# Three things the earlier run could not do, all free here:
#   - the neighbourhood is known before placing rather than surveyed after
#   - every placement has its own screen x, so no sprite is ever matched to a cell by which
#     assignment fits best
#   - the map is one this probe created, so nothing of the game's is at risk at any point

# Cells along one row. Screen x is `33.941 * (x - y) + L`, so a step of 3 in x puts them 101.8
# pixels apart -- wider than the 72-pixel donor frame, and six of them span 509 of the 640-pixel
# screen. Screen y is driven by `x + y`, which also varies, so they descend the screen as they go.
FLAT_ROW_Y = 32
FLAT_ROW_X = [26, 29, 32, 35, 38, 41]

# The camera is pointed with `centeron` rather than assumed. Every earlier probe anchored on an
# army and inherited wherever the player had scrolled to; this one has no army and no player.
FLAT_CAMERA = (33, 32)

# Map size, and the block raised for the plateau phase. The block covers every placement cell and
# more than a 3x3 around each, so a mesh sampler cannot see an edge from any of them.
FLAT_MAP = 64
FLAT_BLOCK = (20, 26, 47, 38)  # x0, y0, x1, y1 inclusive

# The raised elevation. `20.3625 * 2.0` is about 41 pixels of output 2 -- far outside the 11-pixel
# residual being chased, so a null result is as readable as a positive one.
FLAT_ELEVATION = "2.0"

FLAT_SPRITE = '["imp/tree4e.imp"]cvx addterrainspritetype'


def _flat_survey(emit, tag: str) -> None:
    """Log elevation and both map2screen calls for every placement cell and its 3x3 neighbours."""
    emit(f"\t\t{-1} 1 {1}{{/zdy exch def")
    emit(f"\t\t{-1} 1 {1}{{/zdx exch def")
    emit("\t\t0 1 " + str(len(FLAT_ROW_X) - 1) + "{/zi exch def")
    emit("\t\t/zcx zrow zi get zdx add def /zcy " + str(FLAT_ROW_Y) + " zdy add def")
    emit("\t\tzcx zcy getelevation /ze exch def")
    emit("\t\tzcx zcy 0 map2screen /zb3 exch def /zb2 exch def /zb1 exch def")
    emit("\t\tzcx zcy ze map2screen /zn3 exch def /zn2 exch def /zn1 exch def")
    emit(
        "\t\t"
        + _log(
            f'"field {tag} "zi" "zdx" "zdy" cell "zcx" "zcy" elev "ze'
            '" z0 "zb1" "zb2" "zb3" ze "zn1" "zn2" "zn3'
        )
    )
    emit("\t\t}for")
    emit("\t\t}for")
    emit("\t\t}for")


def _flat_set_block(emit, x0: int, y0: int, x1: int, y1: int, value: str) -> None:
    """`x y elevation setelevation`, from `tempx tempy rad_val setelevation` in the editor."""
    emit(f"\t\t{x0} 1 {x1}{{/zsx exch def")
    emit(f"\t\t{y0} 1 {y1}{{/zsy exch def")
    emit(f"\t\tzsx zsy {value} setelevation")
    emit("\t\t}for")
    emit("\t\t}for")


def _flat_phase(emit, tag: str, plate: str, shot: str) -> None:
    """Re-render, plate, place on every row cell, photograph, then remove exactly what was placed."""
    # The mesh has to be rebuilt after elevations change or the render keeps the old heights, and
    # the camera is re-pointed because a rebuild is not guaranteed to preserve it.
    emit("\t\trebuild3dmap resetvisibility rendermap refreshdirty")
    emit(f"\t\t{FLAT_CAMERA[0]} {FLAT_CAMERA[1]} centeron")
    emit("\t\trendermap refreshdirty")
    _flat_survey(emit, tag)
    # The plate is taken AFTER the elevation change: each phase is differenced against its own
    # terrain, so the changed mesh never shows up in the sprite difference.
    emit(f'\t\t"{plate}"screencapture')
    for index in range(len(FLAT_ROW_X)):
        emit(f"\t\t/zx zrow {index} get def /zy {FLAT_ROW_Y} def")
        emit("\t\tzx zy getelevation /ze exch def")
        emit("\t\tzx zy 0 map2screen /zb3 exch def /zb2 exch def /zb1 exch def")
        emit("\t\tzx zy ze map2screen /zn3 exch def /zn2 exch def /zn1 exch def")
        emit(
            "\t\t"
            + _log(
                f'"place {tag} {index} cell "zx" "zy" elev "ze'
                '" z0 "zb1" "zb2" "zb3" ze "zn1" "zn2" "zn3'
            )
        )
        emit("\t\tzx zy zt addterrainsprite")
    emit("\t\trendermap refreshdirty")
    emit(f'\t\t"{shot}"screencapture')
    # `zt` was minted by this keypress, so nothing the game placed can be carrying it. The map is
    # this probe's own creation as well, so there is nothing of the game's here to destroy -- the
    # sweep runs anyway, because the next phase needs the row empty.
    emit(
        "\t\t{dup getterrainspritetype zt eq"
        "{destroyterrainsprite}{pop}ifelse}enumterrainsprites"
    )
    emit("\t\trendermap refreshdirty")
    emit("\t\t" + _log(f'"cleanup {tag} done"'))


def flat_ground_body() -> str:
    lines: list[str] = []
    emit = lines.append
    x0, y0, x1, y1 = FLAT_BLOCK

    emit("; ---- BEGIN FLAT GROUND PROBE (generated by tools/engine_probe.py) ----")
    emit(f'ASCII_VAL"{HOTKEY}"0 get')
    emit("{")
    emit("userdict /zdone known not")
    emit("\t{")
    emit("\tuserdict begin")
    emit("\t/zdone true def")
    emit('\t"zprobe.log""abw"file /zlog exch def')
    emit("\t" + _log('"flat ground probe start"'))
    emit("\t/zrow[" + " ".join(str(value) for value in FLAT_ROW_X) + "]def")
    # Build the map. `392 clearmap` is the texture the shipped `generate_simple_game` uses, and
    # clearmap re-runs `mapw maph newmap` before painting it over every cell.
    emit(
        f"\t{{}}gamemodeproc gamemode {FLAT_MAP} {FLAT_MAP} newmap 392 clearmap default_edit_mode"
    )
    emit("\t" + _log(f'"map built "mapw" "maph'))
    emit(f"\t{FLAT_SPRITE} /zt exch def")
    emit("\t" + _log('"sprite type "zt'))

    # Phase A: everything flat. Explicit rather than trusting newmap to zero the mesh -- the whole
    # experiment rests on knowing the elevations, so they are set, not assumed.
    _flat_set_block(emit, 0, 0, FLAT_MAP - 1, FLAT_MAP - 1, "0")
    _flat_phase(emit, "flat", "zp0.bmp", "zs1.bmp")

    # Phase B: a uniform raised block. Cell and neighbourhood agree.
    _flat_set_block(emit, x0, y0, x1, y1, FLAT_ELEVATION)
    _flat_phase(emit, "plateau", "zp1.bmp", "zs2.bmp")

    # Phase C: the block goes back down and only the six placement cells stay raised. Same
    # `getelevation` at every placement cell as phase B, opposite neighbourhood.
    _flat_set_block(emit, x0, y0, x1, y1, "0")
    for index in range(len(FLAT_ROW_X)):
        emit(f"\t\tzrow {index} get {FLAT_ROW_Y} {FLAT_ELEVATION} setelevation")
    _flat_phase(emit, "spike", "zp2.bmp", "zs3.bmp")

    emit("\t" + _log('"flat ground probe done"'))
    emit("\tzlog closefile")
    emit("\tend")
    emit("\t}if")
    emit("}addhotkey")
    emit("; ---- END FLAT GROUND PROBE ----")
    return "\n".join(lines) + "\n"


PROBES = {
    "ladder": lambda: probe_body(),
    "elevation": elevation_body,
    "mapsize": map_size_body,
    "flatground": flat_ground_body,
}


def install(hotkey_source: str, probe: str = "ladder") -> str:
    """Insert a probe before `hotkey.gs`'s final `end`, which the file warns not to pass."""
    if probe not in PROBES:
        raise ValueError(f"unknown probe {probe!r}; choose from {sorted(PROBES)}")
    marker = "\nend ; DO NOT ADD AFTER 'END'!"
    if hotkey_source.count(marker) != 1:
        raise ValueError(
            f"expected exactly one {marker.strip()!r} marker, found "
            f"{hotkey_source.count(marker)}"
        )
    return hotkey_source.replace(marker, "\n" + PROBES[probe]() + marker)


def disable_intro(start_source: str) -> str:
    """Turn off the two startup movies, which cost minutes of every attended run."""
    guard = '\ntrue\n\t{\n\t75 75"smk/imptitle.smk"MODAL playvideo '
    if start_source.count(guard) != 1:
        raise ValueError("START.GS intro guard not found in its expected form")
    return start_source.replace(guard, guard.replace("\ntrue\n", "\nfalse\n", 1), 1)


if __name__ == "__main__":
    import sys

    which = sys.argv[1] if len(sys.argv) > 1 else "ladder"
    print(PROBES[which](), end="")
