"""Generate the GameScript hotkey body for the sprite placement / palette probe.

The probe is a *diagnostic ladder*, not a single measurement. The 2026-09-16 run failed
because a custom terrain sprite type built from an injected archive member registered an id
but rendered nothing, and there was no control that could say why. Four sprite types are now
placed side by side in one capture:

    zt0  shipped type, shipped art      terrainsprites /orchard get
    zt1  custom type,  shipped art      ["imp/tree4e.imp"] cvx addterrainspritetype
    zt2  custom type,  injected copy    ["imp/zzctl.imp"]  cvx addterrainspritetype
    zt3  custom type,  authored palette ["imp/zzpal.imp"]  cvx addterrainspritetype

Whichever rung the ladder breaks on names the cause: the operator, the injection, or the
palette edit. `zzctl.imp` is byte-identical to `imp\\tree4e.imp`, so zt1 versus zt2 isolates
"the engine cannot read an added member" from "our edit broke the file".

Two hazards the previous run walked into, both fixed here:

- `anythingat?` does **not** see terrain sprites, so a cell can read empty and still hold a
  village. `terrainspriteat` then handed back somebody else's outpost and it was destroyed, so
  cleanup never matches on location alone. It does not match on **type** alone either: rung 0
  reuses the *shipped* orchard type, and destroying by that type would delete every orchard the
  map generator placed. Cleanup requires type **and** cell; only the freshly registered ids get
  a second type-only sweep, since nothing else on the map can be carrying them.
- The hotkey auto-repeats while the key is held. A `zdone` flag in `userdict` makes the body
  fire exactly once per launch.

**Locations are packed, not pairs.** `anythinglocation` and `getterrainspritelocation` each
return ONE value, `y * map_width + x`, and `findemptylocation` takes `(location, unittype)` --
two operands. The shipped corpus is the authority here: `anythinglocation xy_to_x_y` appears 31
times, and `/temple_loc temple_id getterrainspritelocation def` stores a single scalar. The
recovered arity table undercounts and must not be used to design an operand order. Reading a
packed location as a pair underflows the stack and kills the body silently: the 2026-09-16 run
logged an empty x beside `9152`, which at map width 128 is cell (64,71).
"""

from __future__ import annotations

# (label, GameScript expression yielding a terrain sprite type id)
SPRITE_TYPES: list[tuple[str, str]] = [
    ("shipped_type_shipped_art", "terrainsprites /orchard get"),
    ("custom_type_shipped_art", '["imp/tree4e.imp"]cvx addterrainspritetype'),
    ("custom_type_injected_copy", '["imp/zzctl.imp"]cvx addterrainspritetype'),
    ("custom_type_authored_palette", '["imp/zzpal.imp"]cvx addterrainspritetype'),
]

# Seed offsets from the army cell, one per sprite type. `findemptylocation` walks outward from each
# seed, so the seeds have to be far enough apart that two rungs cannot converge on one cell -- two
# sprites in the same cell makes the ladder unreadable. A cell is about 34 screen pixels of x, and
# the donor frame is 72 wide, so 2 cells is the minimum separation and 4 is comfortable. Laying them
# along one axis also gives four collinear points for the cell-to-screen fit.
SEED_OFFSETS: list[tuple[int, int]] = [(2, 0), (4, 0), (-2, 0), (-4, 0)]

HOTKEY = "z"


def is_freshly_registered(index: int) -> bool:
    """True when the type id is minted by this keypress rather than reused from the game.

    Only a freshly registered id is safe to clean up by type alone: no sprite the probe did not
    place can be carrying it. Rung 0 deliberately reuses a shipped type, and is therefore the one
    rung that must always be matched by cell as well.
    """
    return "addterrainspritetype" in SPRITE_TYPES[index][1]


def _log(text: str) -> str:
    """One `zprobe.log` line. `build_statement` interpolates the non-string tokens."""
    return f"zlog{{{text}}}build_statement writestring zlog carriage_return"


def probe_body() -> str:
    lines: list[str] = []
    emit = lines.append

    emit("; ---- BEGIN SPRITE PLACEMENT PROBE (generated by tools/engine_probe.py) ----")
    emit(f'ASCII_VAL"{HOTKEY}"0 get')
    emit("{")
    emit("userdict /zdone known not")
    emit("\t{")
    emit("\tuserdict begin")
    emit("\t/zdone true def")
    emit('\t"zprobe.log""abw"file /zlog exch def')

    # Settle the map first. The previous plate was captured before any rendermap, so the whole
    # terrain sprite layer appeared in the difference and swamped the subject.
    emit("\trendermap refreshdirty")
    emit('\t"zp0.bmp"screencapture')

    # `anythinglocation` returns ONE PACKED LOCATION, not an x/y pair. The shipped corpus settles it
    # -- `anythinglocation xy_to_x_y` appears 31 times, and you do not decompose an already
    # decomposed pair. The 2026-09-16 run proves it too: its log line printed an empty x and
    # y=9152, which at map width 128 is cell (64,71). Reading it as a pair underflows the stack and
    # kills the body before the first placement.
    emit("\t/zaloc -1 def /zseen false def")
    emit(
        "\tcurrentplayer{zseen not{anythinglocation /zaloc exch def /zseen true def}"
        "{pop}ifelse}enumplayerarmies"
    )
    emit("\tzseen")
    emit("\t\t{")
    emit("\t\tzaloc xy_to_x_y /zay0 exch def /zax0 exch def")
    emit("\t\t" + _log('"army loc "zaloc" cell "zax0" "zay0'))

    for index, ((label, expression), (dx, dy)) in enumerate(
        zip(SPRITE_TYPES, SEED_OFFSETS), start=0
    ):
        emit(f"\t\t{expression} /zt{index} exch def")
        # `findemptylocation` takes (location, unittype) -- two operands, not three. Shipped form:
        # `unit_loc UNITTYPELAND findemptylocation /unit_loc exch def`. `x_y_to_xy` packs the pair.
        emit(
            f"\t\tzax0 {dx} add zay0 {dy} add x_y_to_xy UNITTYPELAND findemptylocation "
            f"/zl{index} exch def"
        )
        emit(f"\t\tzl{index} xy_to_x_y /zy{index} exch def /zx{index} exch def")
        emit(f"\t\tzx{index} zy{index} 0 map2screen /zm3 exch def /zm2 exch def /zm1 exch def")
        emit(
            "\t\t"
            + _log(
                f'"type {index} {label} id "zt{index}" loc "zl{index}'
                f'" cell "zx{index}" "zy{index}" m2s "zm1" "zm2" "zm3'
            )
        )
        # Place before resolving the next rung, so `findemptylocation` has a chance to route around
        # a cell this probe just filled.
        emit(f"\t\tzx{index} zy{index} zt{index} addterrainsprite")

    emit("\t\trendermap refreshdirty")
    emit('\t\t"zs1.bmp"screencapture')

    # Cleanup must match the type *and* the cell the probe placed it on. Matching on location alone
    # destroyed a village; matching on type alone is worse, because rung 0 reuses the **shipped**
    # orchard type and would delete every orchard the map generator placed.
    # `getterrainspritelocation` also returns ONE packed location -- shipped uses are
    # `/temple_loc temple_id getterrainspritelocation def` and `... getterrainspritelocation 4 mod`.
    # Compare it against the packed cell the probe placed on, not against a decomposed pair.
    for index in range(len(SPRITE_TYPES)):
        emit(
            f"\t\t{{dup getterrainspritetype zt{index} eq"
            f"{{dup getterrainspritelocation zl{index} eq"
            "{destroyterrainsprite}{pop}ifelse}"
            "{pop}ifelse}enumterrainsprites"
        )
    # A second, type-only pass for the three freshly registered types. Their ids were minted by this
    # keypress, so nothing else on the map can carry them, and it catches anything the first pass
    # skipped -- destroying during an enumeration may advance past an entry.
    for index in range(len(SPRITE_TYPES)):
        if not is_freshly_registered(index):
            continue
        emit(
            f"\t\t{{dup getterrainspritetype zt{index} eq"
            "{destroyterrainsprite}{pop}ifelse}enumterrainsprites"
        )
    emit("\t\trendermap refreshdirty")
    emit('\t\t"zs2.bmp"screencapture')
    emit("\t\t" + _log('"cleanup done"'))
    emit("\t\t}")
    # No army means no anchor cell, so say so in the log rather than placing at (-1,-1).
    emit("\t\t{" + _log('"no army found; nothing placed"') + "}ifelse")

    emit("\tzlog closefile")
    emit("\tend")
    emit("\t}if")
    emit("}addhotkey")
    emit("; ---- END SPRITE PLACEMENT PROBE ----")
    return "\n".join(lines) + "\n"


def install(hotkey_source: str) -> str:
    """Insert the probe before `hotkey.gs`'s final `end`, which the file warns not to pass."""
    marker = "\nend ; DO NOT ADD AFTER 'END'!"
    if hotkey_source.count(marker) != 1:
        raise ValueError(
            f"expected exactly one {marker.strip()!r} marker, found "
            f"{hotkey_source.count(marker)}"
        )
    return hotkey_source.replace(marker, "\n" + probe_body() + marker)


def disable_intro(start_source: str) -> str:
    """Turn off the two startup movies, which cost minutes of every attended run."""
    guard = '\ntrue\n\t{\n\t75 75"smk/imptitle.smk"MODAL playvideo '
    if start_source.count(guard) != 1:
        raise ValueError("START.GS intro guard not found in its expected form")
    return start_source.replace(guard, guard.replace("\ntrue\n", "\nfalse\n", 1), 1)


if __name__ == "__main__":
    print(probe_body(), end="")
